import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta name="google-adsense-account" content="ca-pub-1798246115551950"></meta>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
